export const partners = [
    { name: "Sberbank", logo: "/img/trustedBy/sberbank.svg" },
    { name: "VTB", logo: "/img/trustedBy/vtb.svg" },
    { name: "Gazprom", logo: "/img/trustedBy/gazprom.svg" },
    { name: "Rosneft", logo: "/img/trustedBy/rosneft.svg" },
    { name: "Magnit", logo: "/img/trustedBy/magnet.svg" },
    { name: "Five", logo: "/img/trustedBy/five.svg" },
    { name: "Russian Railways", logo: "/img/trustedBy/russian-railways.svg" },
    { name: "Rostelecom", logo: "/img/trustedBy/rostelecom.svg" },
    { name: "Rosseti", logo: "/img/trustedBy/rosseti.svg" },
    { name: "Post Bank", logo: "/img/trustedBy/post-office-bank.svg" },
    { name: "Gloria Jeans", logo: "/img/trustedBy/gloria-jeans.svg" },
    { name: "Fix Price", logo: "/img/trustedBy/fix-price.svg" },
    { name: "Megafon", logo: "/img/trustedBy/megafon.svg" },
    { name: "Rosgostrah", logo: "/img/trustedBy/rosgostrah.svg" },
    { name: "Invitro", logo: "/img/trustedBy/invitro.svg" },
    { name: "Hemotest", logo: "/img/trustedBy/hemotest.svg" },
    { name: "Rosselkhoznadzor", logo: "/img/trustedBy/rosselkhoznadzor-bank.svg" },
    { name: "Nalchik Sweetness", logo: "/img/trustedBy/nalchik-sweetness.svg" },
    { name: "Ridada", logo: "/img/trustedBy/ridada.svg" },
    { name: "DEA", logo: "/img/trustedBy/dea.svg" },
    { name: "Wester Hyper", logo: "/img/trustedBy/wester-hyper.svg" },
];
